export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const FETCH_STARWARS_SUCCESS = 'FETCH_STARWARS_SUCCESS';
export const FETCH_STARWARS_LOADING = 'FETCH_STARWARS_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';

